name: gvm_flutter
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  app_links: ^6.3.2
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  http: ^1.2.2
  jiffy: ^6.3.1
  mockito: ^5.4.4
  provider: ^6.1.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - .env
